"""Word bank for the typing test.

Roughly the 200 most common English words. Tests are generated by sampling
from this list at request time, so a handful of lines gives effectively
unlimited variety without shipping passages of prose in the image.
"""

WORDS = """
the be to of and a in that have it for not on with he as you do at this but his
by from they we say her she or an will my one all would there their what so up
out if about who get which go me when make can like time no just him know take
people into year your good some could them see other than then now look only
come its over think also back after use two how our work first well way even
new want because any these give day most us man find here thing tell very ask
need feel become leave put mean keep let begin seem help talk turn start might
show hear play run move live believe hold bring happen write sit stand lose pay
meet include continue set learn change lead understand watch follow stop create
speak read spend grow open walk win teach offer remember consider appear buy
serve die send build stay fall cut reach kill remain word life child world school
state family student group country problem hand part place case week company
system program question work night point home water room mother area money story
fact month book eye job business issue side kind head house friend father hour
game line end member law car city name team minute idea kid body back parent face
level office door health person art war history party result change morning
reason research girl guide moment air teacher force education
"""

# dict.fromkeys drops the few accidental repeats while keeping the order,
# so no word is silently weighted twice when sampling.
WORDS = list(dict.fromkeys(WORDS.split()))
