AWSTemplateFormatVersion: '2010-09-09'
Description: Private, immutable ECR repository for Lab 2
# v1.1 
Parameters:
  RepositoryName:
    Type: String
    Default: ecs-app
  CIRoleArn:
    Type: String
    Description: ARN of the GitHub Actions OIDC role allowed to push images (no default)
 
Resources:
  AppRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageTagMutability: IMMUTABLE
      ImageScanningConfiguration: { ScanOnPush: true }
      EncryptionConfiguration: { EncryptionType: AES256 }
      RepositoryPolicyText:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowPushFromCIRoleOnly
            Effect: Allow
            Principal: { AWS: !Ref CIRoleArn }
            Action:
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep the last 15 versioned builds",
                "selection": {
                  "tagStatus": "tagged",
                  "tagPrefixList": ["v"],
                  "countType": "imageCountMoreThan",
                  "countNumber": 15
                },
                "action": { "type": "expire" }
              },
              {
                "rulePriority": 2,
                "description": "Expire untagged images after 30 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 30
                },
                "action": { "type": "expire" }
              }
            ]
          }
      Tags:
        - {Key: Project, Value: lab2-ecs-bluegreen-pipeline}
        - {Key: Environment, Value: lab}
        - {Key: ManagedBy, Value: CloudFormation}
 
Outputs:
  RepositoryUri: {Value: !GetAtt AppRepository.RepositoryUri}
  RepositoryArn: {Value: !GetAtt AppRepository.Arn}
