version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: arn:aws:ecs:eu-north-1:697863031884:task-definition/lab2-app:7
        LoadBalancerInfo:
          ContainerName: "lab2-app"
          ContainerPort: 8080
        PlatformVersion: "LATEST"
